name: upload

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/secrets-uploader

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache only the tiny uploader's deps
      - name: Cache node_modules (uploader only)
        uses: actions/cache@v4
        with:
          path: .github/secrets-uploader/node_modules
          # Hash lockfile if present, else package.json
          key: ${{ runner.os }}-node20-uploader-${{ hashFiles('.github/secrets-uploader/package-lock.json', '.github/secrets-uploader/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node20-uploader-

      - name: Install deps (tiny)
        run: |
          if [ ! -d node_modules ]; then
            if [ -f package-lock.json ]; then
              npm ci --omit=optional --no-audit --no-fund
            else
              npm install --omit=optional --no-audit --no-fund
            fi
          fi

      - name: Show toolkit version
        run: node -p "require('@chainlink/functions-toolkit/package.json').version"

      - name: Upload DON secrets (from GH Actions secrets)
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          MLB_API_KEY: ${{ secrets.MLB_API_KEY }}
          NFL_API_KEY: ${{ secrets.NFL_API_KEY }}
          MLB_ENDPOINT: ${{ secrets.MLB_ENDPOINT }}
          NFL_ENDPOINT: ${{ secrets.NFL_ENDPOINT }}
          # Optional: override TTL in minutes (defaults to 1440 = 24h)
          # DON_TTL_MINUTES: 1440
        run: npm run upload

      - name: Show activeSecrets.json (repo root)
        run: cat ../../activeSecrets.json

      - name: Commit and push updated activeSecrets.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ../../activeSecrets.json
          git commit -m "Update activeSecrets.json [skip ci]" || true
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" "HEAD:${BRANCH}"
