name: Rebuild package-lock on Linux

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebuild-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Rebuild lockfile (Linux)
        run: |
          rm -rf node_modules package-lock.json
          npm install --package-lock-only

      - name: Commit and push lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: rebuild package-lock.json on Linux"
          git push
