name: upload

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Linux-safe install (avoids fsevents). If npm ci fails, fall back to install.
      - name: Install dependencies
        run: |
          npm ci --omit=optional --no-audit --no-fund || npm install --omit=optional --no-audit --no-fund --ignore-scripts

      # Print toolkit version actually installed on the runner
      - name: Show toolkit version
        run: node -p "try{console.log(require('@chainlink/functions-toolkit/package.json').version)}catch(e){console.log('missing')}"

      - name: Upload DON secrets (from GH Actions secrets)
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          MLB_API_KEY: ${{ secrets.MLB_API_KEY }}
          NFL_API_KEY: ${{ secrets.NFL_API_KEY }}
          MLB_ENDPOINT: ${{ secrets.MLB_ENDPOINT }}
          NFL_ENDPOINT: ${{ secrets.NFL_ENDPOINT }}
        run: node upload-secrets.js

      - name: Show activeSecrets.json
        run: cat activeSecrets.json

      - name: Commit and push updated activeSecrets.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add activeSecrets.json
          git commit -m "Update activeSecrets.json [skip ci]" || true
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" "HEAD:${BRANCH}"
